spring.application.name=securevoteledger

ethereum.privateKey=0xcab0ecf160585d26569f5f5098ccfcacad27b90b78f09936bdc72c14ec46734e

ethereum.contractAddress=0xcADd82c5317C720C35040d2B5EB30a0561022bF6
ethereum.rpcUrl=http://127.0.0.1:7545
spring.datasource.url=jdbc:mysql://root:thhJNwHDqFzHdIeQCzClLKPhgTwifwZJ@shinkansen.proxy.rlwy.net:11308/railway
spring.datasource.username=root
spring.datasource.password=thhJNwHDqFzHdIeQCzClLKPhgTwifwZJ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect